#Intro
print("\t\t\t~~~~PYTHON DIALOGUE MAKER~~~~")
print("----------------------------------------------------")
print("\t\t\t   |Make your own dialogue|")
print("=====================================================")
print("\t\t\t\t   ヾ(⌐■_■)ノ♪")
print("=====================================================")
print("=====================================================")
#Name Declarations
name1 = input("Enter 1st Character Name:")
name2 = input("Enter 2nd Character Name:")
#Dialogue Declarations
print("Enter All dialogues of !st Character and press 'Enter Key'")
firstP = ["0","0","0","0","0","0","0","0","0","0",]
firstP[0] = input("1st:")
firstP[1] = input("2nd:")
firstP[2] = input("3rd:")
firstP[3] = input("4th:")
firstP[4] = input("5th:")
firstP[5] = input("6th:")
firstP[6] = input("7th:")
firstP[7] = input("8th:")
firstP[8] = input("9th:")
firstP[9] = input("10th:")

print("Enter All dialogues of 2nd Character and press 'Enter Key'")
SP = ["0","0","0","0","0","0","0","0","0","0",]
SP[0] = input("1st:")
SP[1] = input("2nd:")
SP[2] = input("3rd:")
SP[3] = input("4th:")
SP[4] = input("5th:")
SP[5] = input("6th:")
SP[6] = input("7th:")
SP[7] = input("8th:")
SP[8] = input("9th:")
SP[9] = input("10th:")
print("")
#main dialogue
print("Thank you for giving your valuable inputs.")
print("Now we are processing with it")
print("Procesing...")
print("Procesing...")
print("Procesing...")
print("Here is your dialogue")
print("")
print("")
print("")
print(str(name1)+" : "+str(firstP[0]))
print(str(name2)+" : "+str(SP[0]))
print(str(name1)+" : "+str(firstP[1]))
print(str(name2)+" : "+str(SP[1]))
print(str(name1)+" : "+str(firstP[2]))
print(str(name2)+" : "+str(SP[2]))
print(str(name1)+" : "+str(firstP[3]))
print(str(name2)+" : "+str(SP[3]))
print(str(name1)+" : "+str(firstP[4]))
print(str(name2)+" : "+str(SP[4]))
print(str(name1)+" : "+str(firstP[5]))
print(str(name2)+" : "+str(SP[5]))
print(str(name1)+" : "+str(firstP[6]))
print(str(name2)+" : "+str(SP[6]))
print(str(name1)+" : "+str(firstP[7]))
print(str(name2)+" : "+str(SP[7]))
print(str(name1)+" : "+str(firstP[8]))
print(str(name2)+" : "+str(SP[8]))
print(str(name1)+" : "+str(firstP[9]))
print(str(name2)+" : "+str(SP[9]))
print("")
print("Now copy this Dialogue from here and enjoy itヾ(⌐■_■)ノ♪")
print("")
print("Made with python")
print("Thank you for Choosing us")
print("Developer : ******(SECRET)")
print("My GitHub : https://github.com/DevTroop7007")
